wandb_version: 1

SEED:
  desc: null
  value: 41
DEVICE:
  desc: null
  value: cuda
EPOCHS:
  desc: null
  value: 1
TIMESTEPS:
  desc: null
  value: 5000
N_X:
  desc: null
  value: 100
N_TASKS:
  desc: null
  value: 5
IN_FEATURES:
  desc: null
  value: 1
OUT_FEATURES:
  desc: null
  value: 1
POOL_N_LAYERS:
  desc: null
  value: 30
N_LAYERS_PER_NETWORK:
  desc: null
  value: 5
N_NODES_PER_LAYER:
  desc: null
  value: 32
POOL_LAYER_TYPE:
  desc: null
  value: torch.nn.modules.linear.Linear
ACTION_SPACE_SHAPE:
  desc: null
  value:
  - 3
EPSILON:
  desc: null
  value: 0.1
BATCH_SIZE:
  desc: null
  value: 1
LEARNING_RATE:
  desc: null
  value: 0.01
ACTION_CACHE_SIZE:
  desc: null
  value: 5
NUM_WORKERS:
  desc: null
  value: 0
LOSS_FN:
  desc: null
  value: MSELoss()
SB3_MODEL:
  desc: null
  value: sb3_contrib.ppo_recurrent.ppo_recurrent.RecurrentPPO
SB3_POLICY:
  desc: null
  value: MlpLstmPolicy
LOG_DIR:
  desc: null
  value: runs
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698977909.453048
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
