wandb_version: 1

seed:
  desc: null
  value: 41
device:
  desc: null
  value: cuda
wandb_tag:
  desc: null
  value: evaluation_1227_1349
run_datetime:
  desc: null
  value: '1227_1349'
n_runs:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1
timesteps:
  desc: null
  value: 1000
n_x:
  desc: null
  value: 100
n_tasks:
  desc: null
  value: 3
task_min_loss:
  desc: null
  value: {}
task_max_loss:
  desc: null
  value: {}
in_features:
  desc: null
  value: 1
out_features:
  desc: null
  value: 1
n_pool_hidden_layers:
  desc: null
  value: 9
n_hidden_layers_per_network:
  desc: null
  value: 3
n_layers_per_network:
  desc: null
  value: 5
n_nodes_per_layer:
  desc: null
  value: 40
activation_fn:
  desc: null
  value: relu
pool_layer_type:
  desc: null
  value: torch.nn.modules.linear.Linear
batch_size:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.005
meta_learning_rate:
  desc: null
  value: 0.0003
meta_clip_range:
  desc: null
  value: 0.2
meta_n_steps:
  desc: null
  value: 2048
meta_recurrent_n_steps:
  desc: null
  value: 128
loss_fn:
  desc: null
  value: MSELoss()
sb3_model:
  desc: null
  value: RecurrentPPO
data_dir:
  desc: null
  value: data
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703702994.171086
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
