wandb_version: 1

seed:
  desc: null
  value: 20
device:
  desc: null
  value: cuda
wandb_run:
  desc: null
  value: sac-0.01
n_runs:
  desc: null
  value: 1
epochs:
  desc: null
  value: 10
timesteps:
  desc: null
  value: 2000
n_x:
  desc: null
  value: 100
n_tasks:
  desc: null
  value: 2
task_min_loss:
  desc: null
  value: {}
task_max_loss:
  desc: null
  value: {}
in_features:
  desc: null
  value: 1
out_features:
  desc: null
  value: 1
n_hidden_layers_per_network:
  desc: null
  value: 1
n_layers_per_network:
  desc: null
  value: 3
n_nodes_per_layer:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.005
nudge_size:
  desc: null
  value: 0.01
action_cache_size:
  desc: null
  value: 5
num_workers:
  desc: null
  value: 0
loss_fn:
  desc: null
  value: MSELoss()
sb3_model:
  desc: null
  value: SAC
sb3_policy:
  desc: null
  value: MlpPolicy
log_dir:
  desc: null
  value: slurm
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702774141.485501
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
