wandb_version: 1

seed:
  desc: null
  value: 41
device:
  desc: null
  value: cuda
pretrain:
  desc: null
  value: false
n_runs:
  desc: null
  value: 1
epochs:
  desc: null
  value: 5
timesteps:
  desc: null
  value: 1000
n_x:
  desc: null
  value: 100
n_tasks:
  desc: null
  value: 5
task_min_loss:
  desc: null
  value: {}
task_max_loss:
  desc: null
  value: {}
in_features:
  desc: null
  value: 1
out_features:
  desc: null
  value: 1
n_pool_hidden_layers:
  desc: null
  value: 15
n_hidden_layers_per_network:
  desc: null
  value: 3
n_layers_per_network:
  desc: null
  value: 5
n_nodes_per_layer:
  desc: null
  value: 40
pool_layer_type:
  desc: null
  value: torch.nn.modules.linear.Linear
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.005
discount_factor:
  desc: null
  value: 0.95
action_cache_size:
  desc: null
  value: 5
num_workers:
  desc: null
  value: 0
loss_fn:
  desc: null
  value: MSELoss()
sb3_model:
  desc: null
  value: RecurrentPPO
sb3_policy:
  desc: null
  value: MlpLstmPolicy
log_dir:
  desc: null
  value: wandb
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702489508.162261
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
