wandb_version: 1

seed:
  desc: null
  value: 391
device:
  desc: null
  value: cuda
wandb_tag:
  desc: null
  value: ''
run_datetime:
  desc: null
  value: ''
n_runs:
  desc: null
  value: 1
epochs:
  desc: null
  value: 3
timesteps:
  desc: null
  value: 50
n_x:
  desc: null
  value: 100
n_tasks:
  desc: null
  value: 3
task_min_loss:
  desc: null
  value:
    '0': .inf
    '2': .inf
    '1': .inf
task_max_loss:
  desc: null
  value:
    '0': -.inf
    '2': -.inf
    '1': -.inf
in_features:
  desc: null
  value: 1
out_features:
  desc: null
  value: 1
n_pool_hidden_layers:
  desc: null
  value: 9
n_hidden_layers_per_network:
  desc: null
  value: 3
n_layers_per_network:
  desc: null
  value: 5
n_nodes_per_layer:
  desc: null
  value: 40
pool_layer_type:
  desc: null
  value: torch.nn.modules.linear.Linear
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.01
meta_learning_rate:
  desc: null
  value: 0.001
meta_clip_range:
  desc: null
  value: 0.2
meta_n_steps:
  desc: null
  value: 128
loss_fn:
  desc: null
  value: MSELoss()
sb3_model:
  desc: null
  value: PPO
data_dir:
  desc: null
  value: data
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703519517.649731
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
